### ISSUE TITLE
Achivements error on Linux

### ISSUE THREAD

**Issue by gnidorah** [wolfetplayer/RealRTCW#24]
Hi I'm playing on Linux using non-steam release (since steam one doesn't build) https://github.com/wolfetplayer/RealRTCW/archive/3.1n.tar.gz with Steam mod data

However after recent mod update on Steam, game doesn't loads due not found achivements

Please fix it somehow. Thanks

**Comment by wolfetplayer** [comment]
You're using data from the Steam version using non steam release? Obviously It will not work obviously because steam mod data have references to steam achievements. 
Use the non steam data from moddb and non steam branch from github and you're gonna be just fine. 

Data is equal for both ModDB and Steam versions. (besides achievements stuff)

**Comment by gnidorah** [comment]
@wolfetplayer 
Ok, I will do so until there will be Linux support in Steam
Thanks!
